### PR TITLE
Fix `Match cannot be followed by use space`

### LINKED ISSUE #3726: Match cannot be followed by `use space`
**Describe the bug (__required__)**
Nebula 2.6 support the ngql: "use space; match (v:person) return v"

for the latest version nebula(nightly 0106), the same statement is not supported.
image

**How To Reproduce(__required__)**
1. create tag tag_b(col double)
2. create tag index aaa on tag_b(col)
3. insert vertex tag_b(col) values "2":(2.2)
4. use test;match (v:tag_b) return v

### PR DESCRIPTION
**Pull request by jackwener**
#### What type of PR is this?
- [x] bug
- [ ] feature
- [ ] enhancement

#### What problem(s) does this PR solve?
Issue(s) number:  close #3726

Description:
Fix bug

#### How do you solve it?

skip some conditions
  
#### Checklist:
Tests:
- [ ] Unit test(positive and negative cases)
- [x] Function test
- [ ] Performance test
- [ ] N/A

Affects:
- [ ] Documentation affected (Please add the label if documentation needs to be modified.)
- [ ] Incompatibility (If it breaks the compatibility, please describe it and add the label.）
- [ ] If it's needed to cherry-pick (If cherry-pick to some branches is required, please label the destination version(s).)
- [ ] Performance impacted: Consumes more CPU/Memory

#### Release notes:

Please confirm whether to be reflected in release notes and how to describe:
> ex. Fixed the bug .....

### CODE REVIEW

File: src/graph/planner/SequentialPlanner.h [hunk 1]
```diff
@@ -6,6 +6,8 @@
 #ifndef GRAPH_PLANNER_PLANNERS_SEQUENTIALPLANNER_H_
 #define GRAPH_PLANNER_PLANNERS_SEQUENTIALPLANNER_H_
 
+#include <memory>
```
Comment (Aiee) [inline src/graph/planner/SequentialPlanner.h:9]: Seems unused

File: src/graph/validator/Validator.cpp [hunk 2]
```diff
@@ -299,8 +302,14 @@ std::vector<std::string> Validator::getOutColNames() const {
 Status Validator::appendPlan(PlanNode* node, PlanNode* appended) {
   DCHECK(node != nullptr);
   DCHECK(appended != nullptr);
-  if (!node->isSingleInput()) {
-    return Status::SemanticError("%s not support to append an input.",
+
+  std::set<PlanNode::Kind> skipTypeSet = {PlanNode::Kind::kSwitchSpace};
+
+  // Note: there's check which forbids sentence like `[dql(or other) ngql];[cypher]`.
```
Comment (Shylock-Hg) [inline src/graph/validator/Validator.cpp:308]: This check don't report error?

Comment (jackwener) [reply src/graph/validator/Validator.cpp:306]: > This check don't report error?

like `use nba; match (n:player) return n limit 1`, it's right

Comment (Shylock-Hg) [reply src/graph/validator/Validator.cpp:306]: But we have disable mixed ngql and cypher as you said in this comment.

File: src/graph/validator/Validator.cpp [hunk 3]
```diff
@@ -299,8 +300,14 @@ std::vector<std::string> Validator::getOutColNames() const {
 Status Validator::appendPlan(PlanNode* node, PlanNode* appended) {
   DCHECK(node != nullptr);
   DCHECK(appended != nullptr);
-  if (!node->isSingleInput()) {
-    return Status::SemanticError("%s not support to append an input.",
+
+  std::set<PlanNode::Kind> skipTypeSet = {PlanNode::Kind::kSwitchSpace};
```
Comment (nevermore3) [inline src/graph/validator/Validator.cpp:304]: No need to use the set container

**Review by nevermore3 — DISMISSED** [review]

**Review by Aiee — DISMISSED** [review]

File: tests/tck/features/match/MultiLineMultiQueryParts.feature [hunk 4]
```diff
@@ -0,0 +1,272 @@
...
+      WITH n, n.player.name AS n1 ORDER BY n1 LIMIT 10
+      RETURN m
+      """
+    Then a SemanticError should be raised at runtime: Alias used but not defined: `m'
+    When executing query:
+      """
+      USE nba;
+      MATCH (v:player)-[e]-(v:team) RETURN v, e
+      """
+    Then a SemanticError should be raised at runtime: `v': Redefined alias in a single path pattern.
```
Comment (Shylock-Hg) [inline tests/tck/features/match/MultiLineMultiQueryParts.feature:272]: Add a test case like `yield 1; match ...`

**Review by nevermore3 — DISMISSED** [review]

File: tests/tck/features/match/MultiLineMultiQueryParts.feature (hunk 4 above)
Comment (jackwener) [reply tests/tck/features/match/MultiLineMultiQueryParts.feature:272]: just for USE space

File: tests/tck/features/match/MultiLineMultiQueryParts.feature [hunk 5]
```diff
@@ -0,0 +1,272 @@
...
+      | "Tim Duncan" | "Boris Diaw"        | NULL |
+      | "Tim Duncan" | "Danny Green"       | NULL |
+      | "Tim Duncan" | "Danny Green"       | NULL |
+      | "Tim Duncan" | "Dejounte Murray"   | NULL |
+      | "Tim Duncan" | "LaMarcus Aldridge" | NULL |
+      | "Tim Duncan" | "LaMarcus Aldridge" | NULL |
+      | "Tim Duncan" | "Manu Ginobili"     | NULL |
+      | "Tim Duncan" | "Manu Ginobili"     | NULL |
+      | "Tim Duncan" | "Manu Ginobili"     | NULL |
+    # Below scenario is not suppoted for the execution plan has a scan.
```
Comment (Aiee) [inline tests/tck/features/match/MultiLineMultiQueryParts.feature:192]: supported

File: src/graph/planner/SequentialPlanner.cpp [hunk 6]
```diff
@@ -24,6 +24,10 @@ StatusOr<SubPlan> SequentialPlanner::transform(AstContext* astCtx) {
   subPlan.root = validators.back()->root();
   ifBuildDataCollect(subPlan, qctx);
   for (auto iter = validators.begin(); iter < validators.end() - 1; ++iter) {
+    // Remove left tail kStart plannode before append plan.
+    // It allows that kUse sentence append kMatch Sentence.
```
Comment (Aiee) [inline src/graph/planner/SequentialPlanner.cpp:28]: `// It allows that kUse sentence to append kMatch Sentence.`

File: src/graph/planner/SequentialPlanner.cpp [hunk 7]
```diff
@@ -59,5 +63,27 @@ void SequentialPlanner::ifBuildDataCollect(SubPlan& subPlan, QueryContext* qctx)
       break;
   }
 }
+
+// When appending plans, it need to remove left tail plannode.
+// Because the left tail plannode is StartNode that need to remove it,
```
Comment (Aiee) [inline src/graph/planner/SequentialPlanner.cpp:68]: `// Because the left tail plannode is StartNode which needs to be  removed,`

File: src/graph/validator/Validator.h [hunk 8]
```diff
@@ -87,6 +87,10 @@ class Validator {
     exprProps_ = exprProps;
   }
 
+  void setTail(PlanNode* tail) {
```
Comment (Aiee) [inline src/graph/validator/Validator.h:90]: void setTail(const PlanNode* tail)

File: tests/tck/features/match/MultiLineMultiQueryParts.feature [hunk 9]
```diff
@@ -0,0 +1,272 @@
...
+      | "Tim Duncan" | "Aron Baynes" | "Celtics"    |
+      | "Tim Duncan" | "Aron Baynes" | "Pistons"    |
+      | "Tim Duncan" | "Aron Baynes" | "Spurs"      |
+      | "Tim Duncan" | "Aron Baynes" | "Tim Duncan" |
+      | "Tim Duncan" | "Boris Diaw"  | "Hawks"      |
+      | "Tim Duncan" | "Boris Diaw"  | "Hornets"    |
+      | "Tim Duncan" | "Boris Diaw"  | "Jazz"       |
+      | "Tim Duncan" | "Boris Diaw"  | "Spurs"      |
+      | "Tim Duncan" | "Boris Diaw"  | "Suns"       |
+      | "Tim Duncan" | "Boris Diaw"  | "Tim Duncan" |
```
Comment (Aiee) [inline tests/tck/features/match/MultiLineMultiQueryParts.feature:49]: What's the reason to have these 2 cases? Aren't they both in form of  `use...; match...` ?

File: tests/tck/features/match/MultiLineMultiQueryParts.feature [hunk 10]
```diff
@@ -0,0 +1,272 @@
...
+      USE nba;
+      MATCH (m:player{name:"Tim Duncan"})-[:like]-(n)--()
+      WITH  m,n
+      MATCH (m)--(n)
+      RETURN count(*) AS scount
+      """
+    Then the result should be, in order:
+      | scount |
+      | 270    |
+    # Below scenario is not suppoted for the execution plan has a scan.
```
Comment (Aiee) [inline tests/tck/features/match/MultiLineMultiQueryParts.feature:247]: ditto

File: tests/tck/features/match/MultiLineMultiQueryParts.feature (hunk 9 above)
Comment (jackwener) [reply tests/tck/features/match/MultiLineMultiQueryParts.feature:49]: confirm that some case.

File: src/graph/validator/Validator.h (hunk 8 above)
Comment (jackwener) [reply src/graph/validator/Validator.h:90]: we can set in `.h` file

File: tests/tck/features/match/MultiLineMultiQueryParts.feature (hunk 9 above)
Comment (Aiee) [reply tests/tck/features/match/MultiLineMultiQueryParts.feature:49]: For me, these 2 cases are describing the same scenario. Consider removing it later.

**Review by Aiee — DISMISSED** [review]

**Review by CPWstatic — APPROVED** [review]

File: tests/tck/features/match/MultiLineMultiQueryParts.feature (hunk 4 above)
Comment (Shylock-Hg) [reply tests/tck/features/match/MultiLineMultiQueryParts.feature:225]: Test the error

**Review by nevermore3 — APPROVED** [review]

File: tests/tck/features/match/MultiQueryParts.feature [hunk 11]
```diff
@@ -26,25 +26,6 @@ Feature: Multi Query Parts
       | "Tim Duncan" | "Boris Diaw"  | "Spurs"      |
       | "Tim Duncan" | "Boris Diaw"  | "Suns"       |
       | "Tim Duncan" | "Boris Diaw"  | "Tim Duncan" |
-    When executing query:
```
Comment (Shylock-Hg) [inline tests/tck/features/match/MultiQueryParts.feature:29]: Why delete this?
