### PR TITLE
Fix get wrong data when multi tags have same prop name

### LINKED ISSUE #581: Return value not correct when a vertex has same name in multiple tags
First, I create three tags and an edge
```
CREATE TAG course(name string, credits int)
CREATE TAG building(name string)
CREATE TAG student(name string, age int, gender string)
CREATE EDGE select(grade int)
```
Then, insert the following data
```
INSERT VERTEX course(name, credits),building(name) VALUES 102:("English", 6, "No11");
INSERT VERTEX student(name, age, gender) VALUES 202:("Jane", 17, "female");
INSERT EDGE select (grade) VALUES 202 -> 102:(3);
```
when query
```
GO FROM 202 OVER select YIELD $^[student].name AS Student, $$[course].name AS Curriculum, select.grade AS Grade, $$[building].name AS location
```

return unexpected Curriculum

### PR DESCRIPTION
**Pull request by laura-ding**
close #581 
Before send to storaged, sort properties by tag, and read them in the order they are sent.

### CODE REVIEW

File: src/graph/GoExecutor.h [hunk 1]
```diff
@@ -154,13 +154,17 @@ class GoExecutor final : public TraverseExecutor {
...
     public:
-        VariantType get(VertexID id, const std::string &prop) const;
+        VariantType get(VertexID id, int64_t index) const;
         void add(const storage::cpp2::QueryResponse &resp);
         const auto* schema() const {
             return schema_.get();
         }
 
     private:
+        // The schema include multi vertexes, and multi tags of one vertex
```
Comment (zlcook) [inline src/graph/GoExecutor.h]: Typo:  vertexes -> vertices

File: src/graph/GoExecutor.h [hunk 2]
```diff
@@ -154,13 +154,17 @@ class GoExecutor final : public TraverseExecutor {
...
+        // eg: get 3 vertexex, vertex A has tag1.prop1, vertex B has tag2.prop2,
```
Comment (zlcook) [inline src/graph/GoExecutor.h]: ditto

File: src/graph/GoExecutor.h (hunk 1 above)
Comment (laura-ding) [reply src/graph/GoExecutor.h]: `vertexes` and `vertices` are all right

**Comment by laura-ding** [comment]
jenkins go

File: src/graph/test/DataTest.cpp [hunk 3]
```diff
@@ -106,6 +106,26 @@ AssertionResult DataTest::prepareSchema() {
                                << " failed, error code "<< static_cast<int32_t>(code);
         }
     }
+    // Test same propName diff tyep in diff tags
```
Comment (whitewum) [inline src/graph/test/DataTest.cpp]: typo

File: src/graph/test/DataTest.cpp [hunk 4]
```diff
@@ -106,6 +106,26 @@ AssertionResult DataTest::prepareSchema() {
...
+    // Test same propName same type in diff tags
+    {
+        cpp2::ExecutionResponse resp;
+        std::string cmd = "CREATE TAG interest(name string)";
+        auto code = client_->execute(cmd, resp);
+        if (cpp2::ErrorCode::SUCCEEDED != code) {
+            return TestError() << "Do cmd:" << cmd
+                               << " failed, error code "<< static_cast<int32_t>(code);
+        }
+    }
```
Comment (whitewum) [inline src/graph/test/DataTest.cpp]: 1. how about use for-loop to create? because I don't see any case to cover: add 10000000 tags/edge_types.
```
for ()

2. create tag xxx+i (name int, name2 string)

2. create tag xxy+i (name string, name2 int)
```

File: src/graph/test/DataTest.cpp [hunk 5]
```diff
@@ -269,6 +289,62 @@ TEST_F(DataTest, InsertVertex) {
...
+        ASSERT_EQ(cpp2::ErrorCode::SUCCEEDED, code);
+        std::vector<std::tuple<std::string, int64_t, std::string, int64_t, int64_t>> expected = {
+            {"Joy", 90, "Petter", 19, 456},
+        };
+        ASSERT_TRUE(verifyResult(resp, expected));
+    }
+    // Test same prop name same type in diff tags
+    {
+        cpp2::ExecutionResponse resp;
+        std::string cmd = "INSERT VERTEX person(name, age),interest(name) "
```
Comment (whitewum) [inline src/graph/test/DataTest.cpp]: for this test case:

insert vertex person(name, age), interest(name)  

/* 1. can I miss any field? e.g. person(name), interest(name) 
if no, please add a case*/

"VALUES hash(\"Bob\"):(\"Bob\", 19, \"basketball\")";

/* 2. can I miss any filed? e.g."VALUES hash(\"Bob\"):(\"Bob\", /*19,*/ \"basketball\")";

if no, please add a case */
