### PR TITLE
Fix coalesce bug

### LINKED ISSUE #3522: Unknown function `coalesce'.
**Please check the FAQ documentation before raising an issue**

```
(root@nebula) [sf1]> return coalesce(1, null);
[ERROR (-1004)]: SyntaxError: Unknown function  near `coalesce'
```

### PR DESCRIPTION
**Pull request by jackwener**
#### What type of PR is this?
- [x] bug
- [ ] feature
- [ ] enhancement

#### What problem(s) does this PR solve?
Issue(s) number: 
close #3522

Description:
The last implementation is wrong, because the parameter is `List` instead of unfixed param

#### How do you solve it?

use unfixed param
  
#### Checklist:
Tests:
- [x] Unit test(positive and negative cases)
- [ ] Function test
- [ ] Performance test
- [ ] N/A

Affects:
- [ ] Documentation affected (Please add the label if documentation needs to be modified.)
- [ ] Incompatibility (If it breaks the compatibility, please describe it and add the label.）
- [x] If it's needed to cherry-pick (If cherry-pick to some branches is required, please label the destination version(s).)
- [ ] Performance impacted: Consumes more CPU/Memory

#### Release notes:

Please confirm whether to be reflected in release notes and how to describe:
> ex. Fixed the bug .....

### CODE REVIEW

**Review by nevermore3 — APPROVED** [review]

**Review by CPWstatic — APPROVED** [review]

File: src/common/function/FunctionManager.cpp [hunk 1]
```diff
@@ -2092,29 +2092,15 @@ FunctionManager::FunctionManager() {
   {
     auto &attr = functions_["coalesce"];
     attr.minArity_ = 1;
-    attr.maxArity_ = 1;
+    attr.maxArity_ = INT64_MAX;
```
Comment (jievince) [inline src/common/function/FunctionManager.cpp:2095]: emmm, Seems it's not unachievable in the current FunctionManager. Plz have a look at the function signature `    {"coalesce",
     {
         TypeSignature({Value::Type::LIST}, Value::Type::__EMPTY__),
     }},`

Comment (jievince) [reply src/common/function/FunctionManager.cpp:2095]: Sorry, I'm wrong. Add `coalese` to `variadicFunReturnType_` is ok.

**Review by nevermore3 — APPROVED** [review]

**Review by jievince — APPROVED** [review]
