### PR TITLE
Fixed crash problem due to meta not ready

### LINKED ISSUE #766: graphd crashed in the release beta
nebula version 1.0.0, Git: 1406e57, Build Time: Aug 14 2019 14:38:33 

image

### PR DESCRIPTION
**Pull request by dutor**
Fixes #766

### CODE REVIEW

File: src/graph/GraphService.cpp [hunk 1]
```diff
@@ -14,17 +14,22 @@
...
-    executionEngine_->init(std::move(ioExecutor));
-    authenticator_ = std::make_unique<SimpleAuthenticator>();
+GraphService::GraphService() {
 }
 
 
 GraphService::~GraphService() = default;
 
 
+Status GraphService::init(std::shared_ptr<folly::IOThreadPoolExecutor> ioExecutor) {
```
Comment (whitewum) [inline src/graph/GraphService.cpp]: good !
