### PR TITLE
Clear the code associated with Add/Remove Hosts

### LINKED ISSUE #736: Remove add/remove hosts steps
Now we discover hosts automatically. 
To avoid one host without registered disturb our cluster,  we support clusterID.

Now it's time to remove the  "add/remove hosts"  steps.
There are two actions:
1.  Set the flag --hosts_whitelist_enabled=false by default.  We need to adjust many UTs in this step. 
2.  Remove the code about add/remove hosts.

### LINKED ISSUE #782: [bug] insert empty prop errors
I add two hosts (in fact they are the same machine)

If I add vertex with property, it's ok

If I add vertex with no property. It's internal error.

image

image

I'm not sure it's about two hosts or empty prop, but it's easy to reproduce.

### PR DESCRIPTION
**Pull request by zhangguoqing**
close #736
close #782

### CODE REVIEW

**Comment by zhangguoqing** [comment]
Jenkins go!

File: src/meta/processors/partsMan/ListHostsProcessor.cpp [hunk 1]
```diff
@@ -45,19 +47,24 @@ StatusOr<std::vector<cpp2::HostItem>> ListHostsProcessor::allHostsWithStatus(
...
+        if (now - info.lastHBTimeInSec_ < FLAGS_removed_threshold_sec) {
+            if (now - info.lastHBTimeInSec_ < FLAGS_expired_threshold_sec) {
+                item.set_status(cpp2::HostStatus::ONLINE);
+            } else {
+                item.set_status(cpp2::HostStatus::OFFLINE);
+            }
+            hostItems.emplace_back(item);
         } else {
-            item.set_status(cpp2::HostStatus::OFFLINE);
+            removeHostsKey.emplace_back(iter->key());
```
Comment (dangleptr) [inline src/meta/processors/partsMan/ListHostsProcessor.cpp]: That's cool.

File: src/meta/test/MetaClientTest.cpp [hunk 2]
```diff
@@ -503,178 +495,6 @@ TEST(MetaClientTest, HeartbeatTest) {
     ASSERT_EQ(1, ActiveHostsMan::getActiveHosts(sc->kvStore_.get()).size());
 }
 
-class TestMetaService : public cpp2::MetaServiceSvIf {
```
Comment (dangleptr) [inline src/meta/test/MetaClientTest.cpp]: Why remove the UTs

Comment (dangleptr) [reply src/meta/test/MetaClientTest.cpp]: The UTs are used to test "retry" logic,   maybe we could use another interface instead of "addHosts"

Comment (zhangguoqing) [reply src/meta/test/MetaClientTest.cpp]: Because the `addHosts` interface has been removed, I also deleted the UT here.  And which interface do we want to use instead of it ?

File: src/meta/processors/partsMan/ListHostsProcessor.cpp (hunk 1 above)
Comment (zhangguoqing) [reply src/meta/processors/partsMan/ListHostsProcessor.cpp]: thx. :)

File: src/meta/test/MetaClientTest.cpp (hunk 2 above)
Comment (dangleptr) [reply src/meta/test/MetaClientTest.cpp]: For example, you could use "addTag" instead

Comment (zhangguoqing) [reply src/meta/test/MetaClientTest.cpp]: Thx.  After reading the code carefully, I understand the role of those UTs, and have chosen the `heartbeat` instead of `addHosts`.

**Comment by zhangguoqing** [comment]
Jenkins go!
