### PR TITLE
Fix the same name tag and edge in same space #598

### LINKED ISSUE #598: Can tag name be identical to an edge type name within the same space
I defined an edge type named _player2_ , then created a tag named _player2_ in the same space successfully.

image

Should the name be unique within one space?

### PR DESCRIPTION
**Pull request by laura-ding**
close #598

### CODE REVIEW

**Comment by laura-ding** [comment]
jenkins go

File: src/graph/ShowExecutor.cpp [hunk 1]
```diff
@@ -164,13 +164,19 @@ void ShowExecutor::showTags() {
         std::vector<std::string> header{"Name"};
         resp_->set_column_names(std::move(header));
 
+        std::set<std::string> uniqueTags;
```
Comment (whitewum) [inline src/graph/ShowExecutor.cpp]: i think the order doesn't matter. Am I right?

File: src/interface/meta.thrift [hunk 2]
```diff
@@ -11,23 +11,24 @@ namespace go nebula.meta
 include "common.thrift"
 
 enum ErrorCode {
-    SUCCEEDED = 0,
+    SUCCEEDED          = 0,
```
Comment (whitewum) [inline src/interface/meta.thrift]: great

File: src/interface/meta.thrift [hunk 3]
```diff
@@ -11,23 +11,24 @@ namespace go nebula.meta
...
-    E_UNSUPPORTED    = -25,
-    E_NOT_DROP       = -26,
+    E_NO_HOSTS         = -21,
+    E_EXISTED          = -22,
+    E_NOT_FOUND        = -23,
+    E_INVALID_HOST     = -24,
+    E_UNSUPPORTED      = -25,
+    E_NOT_DROP         = -26,
     E_BALANCER_RUNNING = -27,
+    E_CONFLICT         = -28,
```
Comment (whitewum) [inline src/interface/meta.thrift]: why a new errorcode? how about existed? (what about mysql? table vs view)

File: src/graph/ShowExecutor.cpp (hunk 1 above)
Comment (laura-ding) [reply src/graph/ShowExecutor.cpp]: Users can get more friendly read when showing tags or edges

File: src/meta/processors/schemaMan/CreateEdgeProcessor.cpp [hunk 4]
```diff
@@ -11,6 +11,18 @@ namespace meta {
 
 void CreateEdgeProcessor::process(const cpp2::CreateEdgeReq& req) {
     CHECK_SPACE_ID_AND_RETURN(req.get_space_id());
+    {
+        folly::SharedMutex::ReadHolder rHolder(LockUtils::tagLock());
+        auto conflictRet = getTagId(req.get_space_id(), req.get_edge_name());
+        if (conflictRet.ok()) {
+            LOG(ERROR) << "Create Edge Failed :" << req.get_edge_name() << " has same name tag";
```
Comment (dutor) [inline src/meta/processors/schemaMan/CreateEdgeProcessor.cpp]: No space before `:`

_Failed to create edge `edge_type`: already exists.

File: src/meta/processors/schemaMan/CreateTagProcessor.cpp [hunk 5]
```diff
@@ -11,17 +11,31 @@ namespace meta {
 
 void CreateTagProcessor::process(const cpp2::CreateTagReq& req) {
     CHECK_SPACE_ID_AND_RETURN(req.get_space_id());
+    {
+        // if there is an edge of the same name
+        folly::SharedMutex::ReadHolder rHolder(LockUtils::edgeLock());
+        auto conflictRet = getEdgeType(req.get_space_id(), req.get_tag_name());
+        if (conflictRet.ok()) {
+            LOG(ERROR) << "Create Tag Failed :" << req.get_tag_name() << " has same name edge";
```
Comment (dutor) [inline src/meta/processors/schemaMan/CreateTagProcessor.cpp]: ditto.

File: src/meta/processors/schemaMan/CreateTagProcessor.cpp [hunk 6]
```diff
@@ -11,17 +11,31 @@ namespace meta {
 
 void CreateTagProcessor::process(const cpp2::CreateTagReq& req) {
     CHECK_SPACE_ID_AND_RETURN(req.get_space_id());
+    {
+        // if there is an edge of the same name
```
Comment (dutor) [inline src/meta/processors/schemaMan/CreateTagProcessor.cpp]: Also add this comment to the edge creation.

File: src/meta/processors/schemaMan/CreateEdgeProcessor.cpp [hunk 7]
```diff
@@ -11,6 +11,20 @@ namespace meta {
 
 void CreateEdgeProcessor::process(const cpp2::CreateEdgeReq& req) {
     CHECK_SPACE_ID_AND_RETURN(req.get_space_id());
+    {
+        // if there is an tag of the same name
+        folly::SharedMutex::ReadHolder rHolder(LockUtils::tagLock());
```
Comment (wadeliuyi) [inline src/meta/processors/schemaMan/CreateEdgeProcessor.cpp]: In multithread env, we can not separate this check in two lock, because between read.unlock and write.lock, other thread may insert some same record.

File: src/meta/processors/schemaMan/CreateTagProcessor.cpp [hunk 8]
```diff
@@ -11,17 +11,32 @@ namespace meta {
...
+        folly::SharedMutex::ReadHolder rHolder(LockUtils::edgeLock());
```
Comment (wadeliuyi) [inline src/meta/processors/schemaMan/CreateTagProcessor.cpp]: ditto

File: src/meta/processors/schemaMan/CreateEdgeProcessor.cpp (hunk 7 above)
Comment (laura-ding) [reply src/meta/processors/schemaMan/CreateEdgeProcessor.cpp]: Good catch! I have to think about it, I think to use the same lock to do it, but it will handle slower in tag and edge. It is hard to happen when thread A creates tag tagName, thread B create edge tagName at the same timestamp.

Comment (dutor) [reply src/meta/processors/schemaMan/CreateEdgeProcessor.cpp]: @wadeliuyi We might as well leave this potential race condition problem to address in the future.

@laura-ding Better to add a TODO here.

Comment (wadeliuyi) [reply src/meta/processors/schemaMan/CreateEdgeProcessor.cpp]: but "hard to happen" not mean "do not happen", and create tag and edge is not the key path of our program, so performance is not key point?
