### PR TITLE
Issue  #1827  Fixed an error when using update sentence.

### LINKED ISSUE #1827: Update syntax splicing 'use space' error
Any update syntax will report such an error：

-  message: "Please choose a graph space with `USE spaceName' firstly"

### PR DESCRIPTION
**Pull request by monadbobo**
Fixed an error that the space could not be found when executing multiple statements (use space statements)
when executing update vertex/edge.

for example:

USE issue1827_update;UPDATE VERTEX 100 SET player.age = 31;

close #1827

### CODE REVIEW

**Comment by monadbobo** [comment]
close #1827

File: src/graph/UpdateEdgeExecutor.cpp [hunk 1]
```diff
@@ -242,6 +245,12 @@ void UpdateEdgeExecutor::insertReverselyEdge(storage::cpp2::UpdateResponse &&rpc
 
 void UpdateEdgeExecutor::execute() {
     FLOG_INFO("Executing UpdateEdge: %s", sentence_->toString().c_str());
+    auto status = prepareData();
+    if (!status.ok()) {
+        DCHECK(onError_);
+        onError_(std::move(status));
```
Comment (laura-ding) [inline src/graph/UpdateEdgeExecutor.cpp]: here need use `doError`, and remove `DCHECK`

File: src/graph/UpdateVertexExecutor.cpp [hunk 2]
```diff
@@ -185,6 +188,14 @@ void UpdateVertexExecutor::finishExecution(storage::cpp2::UpdateResponse &&rpcRe
 
 void UpdateVertexExecutor::execute() {
     FLOG_INFO("Executing UpdateVertex: %s", sentence_->toString().c_str());
+
+    auto status = prepareData();
+    if (!status.ok()) {
+        DCHECK(onError_);
+        onError_(std::move(status));
```
Comment (laura-ding) [inline src/graph/UpdateVertexExecutor.cpp]: ditto
