### PR TITLE
Fix console couldn't read soft link

### LINKED ISSUE #990: Nebula console doesn't work well for multiline nGQL statements ending with backslash
**Describe the bug(__must be provided__)**
```text
(user@172.28.1.3) [sp]> create tag table(\
  dataset_id string, \
  db_id string, \
); \

(user@172.28.1.3) [sp]> create tag table(\
  dataset_id string, \
  db_id string, \
);
Execution succeeded (Time spent: 2824/3405 us)
```

When nGQL ending with backslash `\` and click ENTER double times, there's no response for the query.

### LINKED ISSUE #1071: Console couldn’t read the nebula-graphd.conf, when the nebula-graphd.conf was a soft link

### PR DESCRIPTION
**Pull request by jievince**
Fixed #1071

### CODE REVIEW

File: src/common/fs/FileUtils.cpp [hunk 1]
```diff
@@ -502,6 +513,14 @@ void FileUtils::Iterator::openFileOrDirectory() {
             status_ = Status::Error("open `%s': %s", path_.c_str(), ::strerror(errno));
             return;
         }
+    } else if (type_ == FileType::SYM_LINK) {
+        auto result = FileUtils::realPath(path_.c_str());
+        if (!result.ok()) {
+            status_ = Status::Error("realPath `%s': %s", path_.c_str(), ::strerror(errno));
```
Comment (dutor) [inline src/common/fs/FileUtils.cpp]: `status_ = std::move(result).status();`

File: src/common/fs/FileUtils.cpp [hunk 2]
```diff
@@ -502,6 +513,14 @@ void FileUtils::Iterator::openFileOrDirectory() {
...
+            return;
+        }
+        path_ = result.value();
```
Comment (dutor) [inline src/common/fs/FileUtils.cpp]: `path_ = std::move(result).value()`

**Comment by laura-ding** [comment]
jenkins go
