### PR TITLE
Fixed recursive unary expression

### LINKED ISSUE #659: nGQL logical not "!" for negative values
"**!**" not working for negative values without parentheses.

### PR DESCRIPTION
**Pull request by dutor**
This PR fixes #659

### CODE REVIEW

**Comment by whitewum** [comment]
> bravo

you can approve this pr if you agree to

File: src/common/filter/test/ExpressionTest.cpp [hunk 1]
```diff
@@ -231,6 +231,8 @@ TEST_F(ExpressionTest, LiteralConstantsRelational) {
         ASSERT_EQ((expected), Expression::asBool(value));               \
     } while (false)
 
+    TEST_EXPR(!-1, false);
+    TEST_EXPR(!!-1, true);
```
Comment (whitewum) [inline src/common/filter/test/ExpressionTest.cpp]: check !!1 != !(1+1)
