### PR TITLE
Fix graphd's crash due to lack of support of xor.

### LINKED ISSUE #4951: graphd crashed executing query
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

**A simpler query to reproduce the crash**:

```txt
OPTIONAL MATCH (n0)-[]->(n0) WHERE (id(n0) == 24) OPTIONAL MATCH (n1)-[]->(n1)-[]-(n1) WHERE (id(n1) IN [1,2,3,4,5,7,8,13,16,18,23]) MATCH (n0)-[e0:EDGE_4]->(n1) WHERE (NOT ((e0.edgeProp_4_3 XOR e0.edgeProp_4_3) OR (e0.edgeProp_4_3 AND e0.edgeProp_4_2))) RETURN count(*)
```

the query that crash graphd:

```txt
OPTIONAL MATCH (n0)-[e0]-(n0)-[e1]->(n1:Label_3{labelProp_3_6: 'Stephen Curry', labelProp_3_2: 'Jason Kidd'}:Label_4{labelProp_4_2: 'Tiago Splitter'}:Label_0{labelProp_0_0: true, labelProp_0_2: 57, labelProp_0_4: true}:Label_1{labelProp_1_1: 'Klay Thompson', labelProp_1_2: 'Rajon Rondo', labelProp_1_3: 'DeAndre Jordan', labelProp_1_4: 176}) WHERE (id(n0) == 27) AND ((n1.Label_3.labelProp_3_3 <= (n1.Label_0.labelProp_0_1 + (- n1.Label_3.labelProp_3_3))) XOR ((NOT n1.Label_4.labelProp_4_0) OR (n1.Label_1.labelProp_1_5 XOR n1.Label_1.labelProp_1_5))) OPTIONAL MATCH (n1:Label_3{labelProp_3_2: 'Jason Kidd', labelProp_3_6: 'Stephen Curry'}:Label_4{labelProp_4_2: 'Tiago Splitter'}:Label_0{labelProp_0_0: true, labelProp_0_2: 57, labelProp_0_4: true}:Label_1{labelProp_1_1: 'Klay Thompson', labelProp_1_2: 'Rajon Rondo', labelProp_1_3: 'DeAndre Jordan', labelProp_1_4: 176})-[]-(n1:Label_3{labelProp_3_6: 'Stephen Curry', labelProp_3_2: 'Jason Kidd'}:Label_4{labelProp_4_2: 'Tiago Splitter'}:Label_0{labelProp_0_0: true, labelProp_0_2: 57, labelProp_0_4: true}:Label_1{labelProp_1_1: 'Klay Thompson', labelProp_1_2: 'Rajon Rondo', labelProp_1_3: 'DeAndre Jordan', labelProp_1_4: 176}) WHERE ((n1.Label_0.labelProp_0_1 < 0.990000) XOR (NOT (n1.Label_4.labelProp_4_0 XOR n1.Label_1.labelProp_1_5))) MATCH (n1:Label_3{labelProp_3_6: 'Stephen Curry', labelProp_3_2: 'Jason Kidd'}:Label_4{labelProp_4_2: 'Tiago Splitter'}:Label_0{labelProp_0_0: true, labelProp_0_2: 57, labelProp_0_4: true}:Label_1{labelProp_1_1: 'Klay Thompson', labelProp_1_2: 'Rajon Rondo', labelProp_1_3: 'DeAndre Jordan', labelProp_1_4: 176})-[e2]-(n0)-[]->(n1:Label_3{labelProp_3_6: 'Stephen Curry', labelProp_3_2: 'Jason Kidd'}:Label_4{labelProp_4_2: 'Tiago Splitter'}:Label_0{labelProp_0_4: true, labelProp_0_0: true, labelProp_0_2: 57}:Label_1{labelProp_1_1: 'Klay Thompson', labelProp_1_2: 'Rajon Rondo', labelProp_1_3: 'DeAndre Jordan', labelProp_1_4: 176}) WHERE ((n1.Label_0.labelProp_0_2 <= ((- n1.Label_1.labelProp_1_4) * n1.Label_4.labelProp_4_1)) AND ((NOT n1.Label_0.labelProp_0_0) XOR (NOT n1.Label_0.labelProp_0_0))) RETURN count(*)
```
The crash stack:

```txt
Core was generated by `/root/src/nebula-ent/build/bin/nebula-graphd --flagfile /root/nebula-chaos-clus'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f02482fe700 (LWP 2063))]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f027ddab859 in __GI_abort () at abort.c:79
#2  0x0000000005d34fca in google::LogMessage::Fail() ()
#3  0x0000000005d380c4 in google::LogMessage::SendToLog() ()
#4  0x0000000005d34a99 in google::LogMessage::Flush() ()
#5  0x0000000005d38779 in google::LogMessageFatal::~LogMessageFatal() ()
#6  0x00000000034633c8 in nebula::graph::ExpressionUtils::pullOrs (expr=0x7f02499fe770) at /data/src/nebula-ent/src/graph/util/ExpressionUtils.cpp:695
#7  0x00000000034669db in nebula::graph::ExpressionUtils::reverseLogicalExpr (expr=0x7f02499fe770) at /data/src/nebula-ent/src/graph/util/ExpressionUtils.cpp:1039
#8  0x0000000003483c6c in nebula::graph::ExpressionUtils::reduceUnaryNotExpr(nebula::Expression const*)::$_24::operator()(nebula::Expression const*) const (this=0x7f01d900a240, e=0x7f02499fe730) at /data/src/nebula-ent/src/graph/util/ExpressionUtils.cpp:486
#9  0x00000000034839f2 in std::_Function_handler<nebula::Expression* (nebula::Expression const*), nebula::graph::ExpressionUtils::reduceUnaryNotExpr(nebula::Expression const*)::$_24>::_M_invoke(std::_Any_data const&, nebula::Expression const*&&) (__functor=...,
    __args=@0x7f02482f1c08: 0x7f02499fe730) at /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/std_function.h:285
#10 0x00000000037e14ff in std::function<nebula::Expression* (nebula::Expression const*)>::operator()(nebula::Expression const*) const (this=0x7f02482f1d80, __args=0x7f02499fe730) at /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/std_function.h:688
#11 0x00000000037e312b in nebula::graph::RewriteVisitor::transform(nebula::Expression const*, std::function<bool (nebula::Expression const*)>, std::function<nebula::Expression* (nebula::Expression const*)>) (expr=0x7f02499fe730, matcher=..., rewriter=...)
    at /data/src/nebula-ent/src/graph/visitor/RewriteVisitor.cpp:551
#12 0x0000000003461d85 in nebula::graph::ExpressionUtils::reduceUnaryNotExpr (expr=0x7f02499fe730) at /data/src/nebula-ent/src/graph/util/ExpressionUtils.cpp:494
#13 0x0000000003462cfd in nebula::graph::ExpressionUtils::filterTransform (filter=0x7f0245d9b960) at /data/src/nebula-ent/src/graph/util/ExpressionUtils.cpp:682
#14 0x0000000003790fea in nebula::graph::MatchValidator::validateFilter (this=0x7f0246800700, filter=0x7f0245d9b960, whereClauseCtx=...) at /data/src/nebula-ent/src/graph/validator/MatchValidator.cpp:323
#15 0x000000000378f650 in nebula::graph::MatchValidator::validateImpl (this=0x7f0246800700) at /data/src/nebula-ent/src/graph/validator/MatchValidator.cpp:64
#16 0x000000000368e1a2 in nebula::graph::Validator::validate (this=0x7f0246800700) at /data/src/nebula-ent/src/graph/validator/Validator.cpp:389
#17 0x00000000036d3250 in nebula::graph::SequentialValidator::validateImpl (this=0x7f0246800380) at /data/src/nebula-ent/src/graph/validator/SequentialValidator.cpp:40
#18 0x000000000368e1a2 in nebula::graph::Validator::validate (this=0x7f0246800380) at /data/src/nebula-ent/src/graph/validator/Validator.cpp:389
#19 0x000000000368d44f in nebula::graph::Validator::validate (sentence=0x7f02499699c0, qctx=0x7f0245617360) at /data/src/nebula-ent/src/graph/validator/Validator.cpp:313
#20 0x000000000359a47b in nebula::graph::QueryInstance::validateAndOptimize (this=0x7f0247f07a20) at /data/src/nebula-ent/src/graph/service/QueryInstance.cpp:93
#21 0x00000000035997e4 in nebula::graph::QueryInstance::execute (this=0x7f0247f07a20) at /data/src/nebula-ent/src/graph/service/QueryInstance.cpp:41
#22 0x000000000358f62a in nebula::graph::QueryEngine::execute (this=0x7f0213c06080, rctx=...) at /data/src/nebula-ent/src/graph/service/QueryEngine.cpp:56
#23 0x00000000035087c8 in nebula::graph::GraphService::future_executeWithParameter(long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, nebula::Value, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, nebula::Value> > > const&)::$_1::operator()(nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> >) (this=0x7f0249a09aa0, ret=...) at /data/src/nebula-ent/src/graph/service/GraphService.cpp:238
```

**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`) 5dd205425

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by xtcyclist**
## What type of PR is this?
- [X] bug
- [ ] feature
- [ ] enhancement

#### Issue(s) number: 
Close #4951 

#### Description:
Lack of support for xor.

## How do you solve it?
Added some methods for xor.

## Checklist:
Tests:
- [ ] Unit test(positive and negative cases)
- [ ] Function test
- [ ] Performance test
- [X] TCK
- [ ] N/A

Affects:
- [ ] Documentation affected (Please add the label if documentation needs to be modified.)
- [ ] Incompatibility (If it breaks the compatibility, please describe it and add the label.）
- [ ] If it's needed to cherry-pick (If cherry-pick to some branches is required, please label the destination version(s).)
- [ ] Performance impacted: Consumes more CPU/Memory

## Release notes:

Please confirm whether to be reflected in release notes and how to describe:
> ex. Fixed the bug .....

### CODE REVIEW

**Review by yixinglu — COMMENTED** [review]
Need some TCK test cases.

**Review by yixinglu — APPROVED** [review]

File: src/graph/util/ExpressionUtils.cpp [hunk 1]
```diff
@@ -1094,8 +1112,12 @@ LogicalExpression *ExpressionUtils::reverseLogicalExpr(LogicalExpression *expr)
   std::vector<Expression *> operands;
   if (expr->kind() == Expression::Kind::kLogicalAnd) {
     pullAnds(expr);
-  } else {
+  } else if (expr->kind() == Expression::Kind::kLogicalOr) {
     pullOrs(expr);
+  } else if (expr->kind() == Expression::Kind::kLogicalXor) {
+    pullXors(expr);
+  } else {
+    LOG(FATAL) << "Invalid logical expression kind: " << static_cast<uint8_t>(expr->kind());
```
Comment (czpmango) [inline src/graph/util/ExpressionUtils.cpp:1120]: Better to use `DCHECK`.

**Review by czpmango — APPROVED** [review]
LGTM
