### PR TITLE
Fix meta would crash when balance in multiple relica

### LINKED ISSUE #1820: Failed to commit logs  导致nebula-storaged服务挂了
具体logs已经发给开发人员。

### PR DESCRIPTION
**Pull request by critical27**
1. As title, introduced in #1786, when recovery failed, the plan would be nullptr.
2. Add an error log when commit failed.

close #1820

### CODE REVIEW

File: src/meta/processors/admin/Balancer.h [hunk 1]
```diff
@@ -106,10 +106,6 @@ class Balancer {
 
     void finish() {
         CHECK(!lock_.try_lock());
```
Comment (bright-starry-sky) [inline src/meta/processors/admin/Balancer.h]: A question，Is the useful now of lock?

Comment (critical27) [reply src/meta/processors/admin/Balancer.h]: Yes, we need to make sure we hold the lock whenever we want to call `finish`
