### PR TITLE
Modify lexical error messages

### LINKED ISSUE #1851: Create Space Failed
I create a space with: `create space zakcophfoyxeflbrzyhmyzjwgktshwczucuipvgloovxvyajxujkgcavpsasmnilakrnzjykhjvlxztgterderrmtnxjpqeqdntzlsmleqiboggxjfxcfjwwwnypidtzeeakpufltekjnvlbvlaazriukoeprzyobrbxqyvtrdgioumcjsuzbshhdwlytiyfoqairfnuyzdcdhknrfihqwekpvowbmzyfuvwjtsnsdrobkcmiwzcotbqjejbrphszjgqfzxsjjgbjpmifhqucesihlluwoglaenezfpwqybzweoefkhnjzqxzfamglidlkfrmnqnelnpctchfcmjpbhhbujravkvuaiocxqazwnpcnchtqscejzepghlupcmkdwoevptsjfqyptkioabzzbbugtlhrxnwcpqzroueeavzwzspcydobydykmuqpszrcushqpiudvussojzvnrlrdtubhuwxoqiwxjxpfngvunpgygkasiiujrmgkvgrfngprhaxrkcqbinthdktzevmiuqypqnlcvjzijetuiahfetaepujczclvbtdrtnimpxsbyndgxymrhxrgjhcshomfvsramisngzcxyhzfpzxzzfvmcysmfwaxnesrpergffstoghekmxqnzmewpzpkkkurzgpoqryxonelqrzizpkqhcetfywuosrgslvevudqduujzaarcdznsfcjnzclbvnkplmxeqbgzpqnsyjrjnwftqawxitesdrjyedtojflcffbbckhzdqpvtqawozlbhxsyzjlizzxiavtozpuqfchydnlhisugkoeldwdplgkymlvnbvpdbzaeayuekxvodhmmfuaxjvmaqjlfqeunosluhrurpvlwsxawvslbuuogmoaifjbkaayywiqksukwebvbbzwvhnvkwhlitviwvuupvrvwupykavuphhfhvvhmoccygdjuknbsbeiamuvtwxzgprsdcccxlgiolqscwemcdqkregcbixgoipscurhfeqiwsfafvtfkjcjohnykzqnwamfkbtistkujbxerqqugbdabyvybcrafatbcmhvrshcgnymabjdtczmfgjvxxqyirteatfhcfznsmefidpplcrtzjnhtkvlbvssavthsgqlhysblgtunrlfsnguzdugoixfprwdjjnzzrhtdxbiecsxjkyndofhyzmpjvfdtblacczuwpopebgigowozhbkmobaropfmzmgduipjemruhucunwxcnnnmfsrptdclvqybpmewdtwpbkrtowxpifueasblhcexmwnpcphvjwdahhnvqtmclvohaofrzmrttbcnguzxqmyxbhkvyulibgxcfelptndhdwyqbixzxkusznskqwjnrzsbkovgutuhijbqhgmsyaiecgdolnbslbjyanirnkdwnnuhiewdxdsjmiaofxjlzowinoepxfoeygursbwkrjwzwkemvuhoktsbfcfksywquqjsovtahhdmrhhjjxocnhxzfkqfzyptapifxhutwpkddapxxhcmfllpjhrxidrpyvintuzsydmcomjklxmmansmsxlwdrbmavvnfsmfqpdpyujzlinolunokrrsfnjaxlifbyhickdzcayxbxofzqkbifbzfshjyxyitzypkqglgaacrdynuxulavhnrtqdxwctugswvtgqsimmdymxxbiuftaqtilzogjnsmfdhqplmcstbwgcndjlnnkjxgaqxbbuvkpwmbsgrcoleqsnzztrzathuthmhlikuzcihkaeijagoqtoqxqyzwrsfkezrqngwzpfkszvkrnddixyroxxpszikscotfrhgzhetroafrlupwrwkxxfrroclhccjzsfoknkvmwpfudyuitelavveigwsausbqlvhsgxzeokormihdokfxdktxcytgoyagipoxcuaqjrnkiufiviyxcoqyisccawmbporhgdlbquknyblznzfhgofdiaqtnhmnxgkbyahpvvogwtszzuxqzmvftcgdgitlxziwobmnstrrzhdluqrbzymeyjevdlqkkmkpbrviqkhcpmerumpvzwduifvsbpljroaunuoifeyodrquhnarxjjkaunhkcdoiqtoueyxxroeqvixjzcfdgmxyjhkxstlucexevsprnnqtjfbkrlhedxnouclkaffayibzeiemdfbuqqramobpvziebyentgsymagtvhzzigjqmxyfywjbxtxjoxawkpgcsyyxmywlderqnifewtmyzgdvbbkihaadehbauqedjmoiduewkybhjnpopanssumfncipahgxvfocueoqnknjiyrmatacfmzzflcutuewhedmjmvtltgobhoxzkafljjdccxonzgetfewxaolwjyyngsofrohxwkkipwvvvzlfswwipfkpktejxvmmiahiorzogaiuwipmsoqcxxffxcgoadojlbymxwqmlvxelkrumuerrpqdokijqfhhiyblcwpgnymidksyaioncrhbwrgfbzsmwxambgzedfwcbxsruzcwhrqzdiwlrjfcjycmvrwfqgidelwoeuokpfssvnukuuuqcdsajistxfpgqrbkcwxwcajmisgoicbyxuyryvucsziphwozdhdddmjcjdsqhvrqjvmhruecetggvabtqwxtyaarhwqevpixlefxsizyvxxxdvdknyedtlelnfnywtbvqxqrosgfxzvxojvapypmnqgzazovbnsitwgeatmcaoipzwwmldrxwjbkzhodhrzmjazvxfzigvetqnpiyrbmunztjpfdkdjfbdbpkbvukqpmwdifowdlanpcauksziuqsftjmvkxddtimkzswrtzzjmvughypfqkbonrhoxihxvipatgyicigponkndnpuyjpvhgemfnosyyszopuukxtsksydkeevepmerjriykkhdhrtmysczasmjiwlrvsmebgroaqyszbyyncsarbsmaqycdeijhilimefikrhtjbrnrsazewipxoyhegdbamknheihduoldfewrtybsnrueynpdrysyjhyoadkmbxdyxhhumiizndazjpkyfmkcafjnyshmrccdmnxihgqmsrdsjvhkqeektzztawnrhycbxpfhstvlkdyehsmaslczhhhtjzrjluqyabgzpdmmfjamdhmrfcvosfojsasltgebwefxtyyghzzqtxjaempocrffqldtkplnrvptvdjwjfuxvmqmlvcqzpenkrgzaqrijgrwjjsppwdbjumxsibpkhyjeexofnsbsfbenscipgkrhnvbqymfzzehfuupghroyplasmzxfqkfhutxhzivqnkpypyhldauuvjcbmxgquosnjxlmlentfejjvzrpxgiseaqsmttbdhxurnvedipaewluwmesnxbodccfxtfpgosgjqfxetvrfyxtryohvwetghlnlrpjprfuexvcetnooizdtsfcatgqgygyfilirmnwjauuqbqfexlxxchmujsqpabgfgbvlpbhpexzdnnwdjnsqwesibosbrumzepglakevcyerambxlwlmbdqowmxofpvlanahzkimzamlzwipkqwavlgajyelsavtzvquqagnwaztmhgtigdhhqtbfzkqfmzchicinbljejliuhdmgxfaioxbpitkshlizdxfhsfqdvrcawitcvgnoyraaqnscwtecllxwkhhzolyamcugiedhvdvsxhlxutnlqrfrffpdpprwxhgqfpirsazndsomaaesflniddxibtzqvzfczixpfbjgsawfnqwprqpghphboiwzehevpukttjvvrgtzaeyvbquwqeberlwwsludklgualtxmpfmcqxrlzlryuvlzdtnfyriymojgugwzfyhialgdmvqfejztgqyxfqxjmvgugexrvmvngkhiwsmjsbonmomifdyvlsthhusgatwcmayfhexipsvbezrgnosjltsdfsqbpasvdrzhhlosoydbubjfbgtktbevfyxnkbiriejblvanhhdzjndbzbmggrxkthmnvxoqecmaisikxzxwbdkoaagxymsbxbbdmlsvxijnomimnfokneghefnaewnbzixmuuwgytaurqcaeauxijyzgtcupjlwvfiztvorakwzmuqhguptebsfeptvncxfcdznhfzhbuhcwrykpdbcasbibujfnghwunagrqahweuvrgoswsnkpyfnzrjebqbxgqdoohpehwpphaeklqtkcbxugdggraieycuizepwnlbhntdaxjjpaufsgchgrxwdvymwgcwwjyjvnhbtmhfastvfxnumahagzuaczvmqjjbkjsxhixoypfylneuijzlweihqfypnhdqokghqnfzwbbkiwhtkwvzkffbissczfiitompvnnrxrrxdmsfzddtobmhzpjxwukykmgkgnpvwvdoboqhqstlglawwhargaqhfvqlzmcjanbbxqcbdsvfahytyzclsbbsmkwpcmnbzmlktierrafgqhzfrkkudzldbcugvlmojbxacihqaroxceylspkvhmboutmlwjejxmdzodkkxhwsinsoeqsebpztldtexgkzvakqsqbhorqpxrtwzexrngcyjkzxxjheyssydmqrmhbljwyxixtponzpyejvdqnqojgmjpobacahckelhvgojybqsdkjfuzbkjhxawtstczjyhgnwtsmtisrogialbxhvsosqipcbufynwwfobckdeylhznjadbzdxssurpsnblvbtknzwnwspexnkutzphanliwoutxcarfiuweodroxlrkwquvmvchbbn
`

It tell me: `SyntaxError: syntax error near `

### PR DESCRIPTION
**Pull request by laura-ding**
close #1851

### CODE REVIEW

File: src/parser/test/ScannerTest.cpp [hunk 1]
```diff
@@ -118,11 +118,16 @@ TEST(Scanner, Basic) {
...
+            auto token = lexer.yylex(&dumyyylval, &dumyyyloc);              \
+            if (token != 0) {                                               \
+                return AssertionFailure() << "Lexical error should've "     \
+                                          << "happened for `" << STR << "'";\
+            } else {                                                        \
+                return AssertionSuccess();                                  \
+            }                                                               \
+        } catch (const std::exception &e) {                                 \
+            LOG(INFO) << e.what() << STR;                                   \
             return AssertionSuccess();                                      \
```
Comment (Shylock-Hg) [inline src/parser/test/ScannerTest.cpp]: Return ok with exception?

Comment (Shylock-Hg) [reply src/parser/test/ScannerTest.cpp]: And seems only need catch the line 122

Comment (laura-ding) [reply src/parser/test/ScannerTest.cpp]: > Return ok with exception?

the scanner will throw exceptions about the error lexical. That's what we expected, so return success.
