### PR TITLE
Remove the pruning of Expression::Kind::kVarProperty in agg.

### LINKED ISSUE #4974: Incorrect `unwind` result
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

Look at the query from nebula below:

```txt
(root@nebula) [gdlancer_index]> MATCH (v0)-[e0]->(v1)<-[e1]-(v2:Label_2) WHERE (id(v0) in [8, 22, 19, 13, 5, 7, 18, 20]) AND (v2.Label_2.Label_2_1_Bool) UNWIND e1.Rel_2_3_Bool AS ua0 RETURN COUNT(*)
+----------+
| COUNT(*) |
+----------+
| 0        |
+----------+
Got 1 rows (time spent 1.975ms/16.773042ms)

Tue, 22 Nov 2022 14:01:21 CST
```

In contrast the same query on same dataset in Neo4j resutn 8 rows:

```txt
$ MATCH (v0)-[e0]->(v1)<-[e1]-(v2:Label_2) WHERE (v0.id in [8, 22, 19, 13, 5, 7, 18, 20]) AND (v2.Label_2_1_Bool) UNWIND e1.Rel_2_3_Bool AS ua0 RETURN COUNT(*)

╒══════════╕
│"COUNT(*)"│
╞══════════╡
│8         │
└──────────┘
```

Look into the details, we found that if there are null values in `e1.Rel_2_3_Bool` Nebula will filter all result:

```txt
(root@nebula) [gdlancer_index]> MATCH (v0)-[e0]->(v1)<-[e1]-(v2:Label_2) WHERE (id(v0) in [8, 22, 19, 13, 5, 7, 18, 20]) AND (v2.Label_2.Label_2_1_Bool) return  e1.Rel_2_3_Bool
+-----------------+
| e1.Rel_2_3_Bool |
+-----------------+
| __NULL__        |
| __NULL__        |
| __NULL__        |
| __NULL__        |
| __NULL__        |
| __NULL__        |
| __NULL__        |
| __NULL__        |
| __NULL__        |
| __NULL__        |
| __NULL__        |
| __NULL__        |
| __NULL__        |
| __NULL__        |
| true            |
| true            |
| true            |
| true            |
| __NULL__        |
| __NULL__        |
| __NULL__        |
| __NULL__        |
| __NULL__        |
| __NULL__        |
| __NULL__        |
| false           |
| __NULL__        |
| __NULL__        |
| __NULL__        |
| __NULL__        |
| __NULL__        |
| true            |
| true            |
| true            |
| __NULL__        |
| __NULL__        |
| __NULL__        |
| __NULL__        |
| __NULL__        |
| __NULL__        |
+-----------------+
Got 40 rows (time spent 2.06ms/15.527916ms)

Tue, 22 Nov 2022 14:08:58 CST

(root@nebula) [gdlancer_index]> MATCH (v0)-[e0]->(v1)<-[e1]-(v2:Label_2) WHERE (id(v0) in [8, 22, 19, 13, 5, 7, 18, 20]) AND (v2.Label_2.Label_2_1_Bool) and e1.Rel_2_3_Bool is not null UNWIND e1.Rel_2_3_Bool AS ua0 RETURN COUNT(*)
+----------+
| COUNT(*) |
+----------+
| 8        |
+----------+
Got 1 rows (time spent 2.494ms/15.922084ms)

Tue, 22 Nov 2022 14:09:05 CST
```
The expected behavior:

**unwind should return the value of the expression itself when the expression is not a list, and filter out the null values**  

**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`) https://github.com/xtcyclist/nebula/tree/fix_ent%231580

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by xtcyclist**
## What type of PR is this?
- [X] bug
- [ ] feature
- [ ] enhancement

#### Issue(s) number: 
Close #4974 

#### Description:
`match (v0:player)-[e0]->(v1) where id(v0) == "Tim Duncan" unwind e0.start_year as a return count(a)
`

$a was pruned in this query, causing the unwind operator to produce NULL dataset, which in the end leads to wrong counting results.

## How do you solve it?

Disable the pruning of `Expression::Kind::kVarProperty` and `Expression::Kind::kInputProperty` in PropertyTrackerVisitor.

## Checklist:
Tests:
- [ ] Unit test(positive and negative cases)
- [ ] Function test
- [ ] Performance test
- [X] TCK

Affects:
- [ ] Documentation affected (Please add the label if documentation needs to be modified.)
- [ ] Incompatibility (If it breaks the compatibility, please describe it and add the label.）
- [ ] If it's needed to cherry-pick (If cherry-pick to some branches is required, please label the destination version(s).)
- [ ] Performance impacted: Consumes more CPU/Memory

## Release notes:

Please confirm whether to be reflected in release notes and how to describe:
> ex. Fixed the bug .....

### CODE REVIEW

File: src/graph/visitor/PropertyTrackerVisitor.cpp [hunk 1]
```diff
@@ -317,8 +317,7 @@ void PropertyTrackerVisitor::visit(AggregateExpression *expr) {
   std::transform(funName.begin(), funName.end(), funName.begin(), ::tolower);
   if (funName == "count") {
     auto kind = expr->arg()->kind();
-    if (kind == Expression::Kind::kConstant || kind == Expression::Kind::kInputProperty ||
-        kind == Expression::Kind::kVarProperty) {
+    if (kind == Expression::Kind::kConstant || kind == Expression::Kind::kInputProperty) {
```
Comment (jievince) [inline src/graph/visitor/PropertyTrackerVisitor.cpp:320]: `kInputProperty`  Could't be ignored.

Comment (xtcyclist) [reply src/graph/visitor/PropertyTrackerVisitor.cpp]: Removed.

**Review by yixinglu — APPROVED** [review]

**Review by yixinglu — APPROVED** [review]

**Review by jievince — APPROVED** [review]
