### PR TITLE
Fix PushFilterDownHashInnerJoinRule

### LINKED ISSUE #5147: Incorrect query result
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

Look at the queries below,

the first query `pa2` is correctly returned:

```txt
(root@nebula) [gdlancer]> MATCH (v0)-[e0]->()<-[e1]-(:Label_2) WHERE (id(v0) in [16, 8, 10, 4, 3, 1, 23, 15, 5, 6, 29]) AND (e0.Rel_0_0_Bool) MATCH (v1:Label_6:Label_3)<-[e2:Rel_1]-(:Label_5)-[e3]->(v2) WHERE (id(v1) in [20, 28, 31, 6, 4, 18, 15, 25, 9, 19, 21]) AND (e0.Rel_0_0_Bool) MATCH p0 = (v2)<-[e4]-()-[e5]->(v3:Label_6) WHERE (e5.Rel_0_0_Bool) WITH min(e3.Rel_2_1_Double) AS pa0, ((- ((((e3.Rel_2_1_Double - e3.Rel_2_1_Double) / (79 / v2.Label_0.Label_0_5_Int)) + e4.Rel_3_3_Int) + (e5.Rel_0_3_Int * e1.Rel_3_3_Int))) / e5.Rel_0_3_Int) AS pa1, e3, v3.Label_6.Label_6_1_Bool AS pa2, (v2.Label_0.Label_0_5_Int / e5.Rel_0_4_Double) AS pa3, 0.089742 AS pa4, ((- 0.756717) == ((- (- e4.Rel_2_1_Double)) - (- v2.Label_0.Label_0_4_Int))) AS pa5, e2 WHERE true RETURN pa2
+------+
| pa2  |
+------+
| true |
| true |
| true |
| true |
| true |
| true |
| true |
| true |
| true |
| true |
| true |
| true |
| true |
| true |
+------+
Got 14 rows (time spent 7.652ms/21.0935ms)

Tue, 27 Dec 2022 17:02:25 CST
```

and if add `pa2` as a filter, graphd complained about `BAD_TYPE` and the total rows is alow wrong:

```txt
(root@nebula) [gdlancer]> MATCH (v0)-[e0]->()<-[e1]-(:Label_2) WHERE (id(v0) in [16, 8, 10, 4, 3, 1, 23, 15, 5, 6, 29]) AND (e0.Rel_0_0_Bool) MATCH (v1:Label_6:Label_3)<-[e2:Rel_1]-(:Label_5)-[e3]->(v2) WHERE (id(v1) in [20, 28, 31, 6, 4, 18, 15, 25, 9, 19, 21]) AND (e0.Rel_0_0_Bool) MATCH p0 = (v2)<-[e4]-()-[e5]->(v3:Label_6) WHERE (e5.Rel_0_0_Bool) WITH min(e3.Rel_2_1_Double) AS pa0, ((- ((((e3.Rel_2_1_Double - e3.Rel_2_1_Double) / (79 / v2.Label_0.Label_0_5_Int)) + e4.Rel_3_3_Int) + (e5.Rel_0_3_Int * e1.Rel_3_3_Int))) / e5.Rel_0_3_Int) AS pa1, e3, v3.Label_6.Label_6_1_Bool AS pa2, (v2.Label_0.Label_0_5_Int / e5.Rel_0_4_Double) AS pa3, 0.089742 AS pa4, ((- 0.756717) == ((- (- e4.Rel_2_1_Double)) - (- v2.Label_0.Label_0_4_Int))) AS pa5, e2 WHERE pa2 RETURN pa2
+----------+
| pa2      |
+----------+
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
+----------+
Got 48 rows (time spent 7.91ms/21.079958ms)

Tue, 27 Dec 2022 17:03:58 CST

```

**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`) 9863ff0cb (community edition)

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by xtcyclist**
## What type of PR is this?
- [X] bug
- [ ] feature
- [ ] enhancement

#### Issue(s) number: 
Close #5147 

#### Description:
When pushing down a filter over a hash join, the output columns of the join were set to those of the filter, causing the aggregate after the join to lose its dependent columns and produce null values. 

## How do you solve it?
When pushing filters over hash joins, the columns of the join shall stay unchanged, since the filter may at most change the cardinality of the join's inputs and never change its columns.

## Checklist:
Tests:
- [ ] Unit test(positive and negative cases)
- [x] Function test
- [ ] Performance test
- [ ] N/A

Affects:
- [ ] Documentation affected (Please add the label if documentation needs to be modified.)
- [ ] Incompatibility (If it breaks the compatibility, please describe it and add the label.）
- [ ] If it's needed to cherry-pick (If cherry-pick to some branches is required, please label the destination version(s).)
- [ ] Performance impacted: Consumes more CPU/Memory

## Release notes:

Please confirm whether to be reflected in release notes and how to describe:
> ex. Fixed the bug .....

### CODE REVIEW

File: src/graph/optimizer/rule/PushFilterDownHashInnerJoinRule.cpp [hunk 1]
```diff
@@ -82,7 +82,7 @@ StatusOr<OptRule::TransformResult> PushFilterDownHashInnerJoinRule::transform(
     newGroupNode->dependsOn(const_cast<OptGroup*>(newJoinGroup));
   } else {
     newInnerJoinNode->setOutputVar(oldFilterNode->outputVar());
-    newInnerJoinNode->setColNames(oldFilterNode->colNames());
+    newInnerJoinNode->setColNames(oldInnerJoinNode->colNames());
```
Comment (jievince) [inline src/graph/optimizer/rule/PushFilterDownHashInnerJoinRule.cpp:85]: Why the output column names of oldFilterNode are different from oldInnerJoinNode?

Comment (xtcyclist) [reply src/graph/optimizer/rule/PushFilterDownHashInnerJoinRule.cpp:85]: yi ge shi filter, yi ge shi join, ying gai bu yi yang ba.

**Review by nevermore3 — APPROVED** [review]

**Review by Aiee — APPROVED** [review]
