### PR TITLE
Fix duration type deduce.

### LINKED ISSUE #3515: Using the duration function to calculate causes client downtime
image

### PR DESCRIPTION
**Pull request by Shylock-Hg**
#### What type of PR is this?
- [x] bug
- [ ] feature
- [ ] enhancement

#### Which issue(s)/PR(s) this PR relates to?
Close #3515 
  
#### Checklist:
- [ ] Documentation affected (Please add the label if documentation needs to be modified.)
- [ ] Incompatibility (If it breaks the compatibility, please describe it and add the corresponding label.）
- [ ] If it's needed to cherry-pick (If cherry-pick to some branches is required, please label the destination version(s).)
- [ ] Performance impacted: Consumes more CPU/Memory

#### Release notes:

Please confirm whether to be reflected in release notes and how to describe:
>                                                                 `

### CODE REVIEW

File: src/common/datatypes/Value.cpp [hunk 1]
```diff
@@ -2012,86 +2012,70 @@ void swap(Value& a, Value& b) {
   b = std::move(temp);
 }
 
-std::ostream& operator<<(std::ostream& os, const Value::Type& type) {
+/*static*/ const std::string Value::toString(Type type) {
```
Comment (Aiee) [inline src/common/datatypes/Value.cpp:2015]: What's the benefit of this change?

Comment (Shylock-Hg) [reply src/common/datatypes/Value.cpp:2015]: Get type name

**Review by jievince — APPROVED** [review]
LGTM

**Review by yixinglu — APPROVED** [review]
