### PR TITLE
fix download always return succeeded

### LINKED ISSUE #4321: Download sst return success but actually failed
**Describe the bug (__required__)**
As title

**Your Environments (__required__)**

* Commit id (e.g. `a3ffc7d8`)
image

**How To Reproduce(__required__)**

image

image

image

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by critical27**
## What type of PR is this?
- [X] bug
- [ ] feature
- [ ] enhancement

#### Issue(s) number: 
Close #4321, #4382

#### Description:
`ProcessUtils::runCommand` will always return ok. So we can't tell whether hdfs command succeeded or not.

## How do you solve it?
Use SubProcess to execute shell command.

## Special notes for your reviewer, ex. impact of this fix, design document, etc:
After this PR, if the hdfs address is illegal, the `show job` is weird (job failed but task succeed), probably same as https://github.com/vesoft-inc/nebula/issues/4263, will try to fix it later.

image

## Checklist:
Tests:
- [ ] Unit test(positive and negative cases)
- [ ] Function test
- [ ] Performance test
- [ ] N/A

Affects:
- [ ] Documentation affected (Please add the label if documentation needs to be modified.)
- [ ] Incompatibility (If it breaks the compatibility, please describe it and add the label.）
- [ ] If it's needed to cherry-pick (If cherry-pick to some branches is required, please label the destination version(s).)
- [ ] Performance impacted: Consumes more CPU/Memory

## Release notes:

Please confirm whether to be reflected in release notes and how to describe:
> ex. Fixed the bug .....

### CODE REVIEW

**Review by liwenhui-soul — APPROVED** [review]

File: src/common/hdfs/HdfsCommandHelper.cpp [hunk 1]
```diff
@@ -5,40 +5,54 @@
...
   auto command = folly::stringPrintf(
       "hdfs dfs -ls hdfs://%s:%d%s", hdfsHost.c_str(), hdfsPort, hdfsPath.c_str());
   LOG(INFO) << "Running HDFS Command: " << command;
-  auto result = ProcessUtils::runCommand(command.c_str());
-  if (result.ok()) {
-    return result.value();
-  } else {
-    return Status::Error(folly::stringPrintf("Failed to run %s", command.c_str()));
+  try {
+    folly::Subprocess proc(std::vector<std::string>({command}));
```
Comment (panda-sheep) [inline src/common/hdfs/HdfsCommandHelper.cpp:23]: 👍

**Review by panda-sheep — APPROVED** [review]
Good

File: src/common/hdfs/HdfsCommandHelper.cpp (hunk 1 above)
Comment (SuperYoko) [inline src/common/hdfs/HdfsCommandHelper.cpp:23]: Here actually may have some trouble with system environment variable.
