### PR TITLE
Return error msg for find and match sentence

### LINKED ISSUE #777: graphd crash at again
dup with #712

### PR DESCRIPTION
**Pull request by laura-ding**
fix #777  and #712

### CODE REVIEW

File: src/graph/test/DataTest.cpp [hunk 1]
```diff
@@ -359,6 +359,23 @@ TEST_F(DataTest, InsertVertex) {
     // TODO: Test insert multi tags, and delete one of them then check other existent
 }
 
+TEST_F(DataTest, FindTest) {
+    {
```
Comment (darionyaphet) [inline src/graph/test/DataTest.cpp]: why don't support some `SUCCEEDED` example ?

Comment (laura-ding) [reply src/graph/test/DataTest.cpp]: Because they have not to be implemented
